<?php

const TEXTY = [
    'hlavicka.ahoj' => 'Ahoj! Já jsem',
    'hlavicka.ja_jsem' => 'Já jsem',
    'domu.o_mne.nadpis' => 'O mně',
    'domu.o_mne.popis' => 'Nějaké supermotivační povídání o mně!',
    'domu.o_mne.jmeno' => 'Jméno',
    'domu.o_mne.datum_narozeni' => 'Datum narození',
    'domu.o_mne.adresa' => 'Adresa',
    'domu.o_mne.email' => 'Email',
    'domu.o_mne.telefon' => 'Telefon',
    'domu.souhrn.vzdelani' => 'Vzdělání',
    'domu.souhrn.zkusenosti' => 'Zkušenosti',
    'domu.souhrn.schopnosti' => 'Schopnosti',
    'domu.sluzby.nadpis' => 'Služby',
    'domu.sluzby.popis' => 'Dobrá bylo ji research, vykonanou gamou anebo učit kormidla žen elektromagnetického závěry kde povlak z viru.',
    'menu.domu' => 'Domů',
    'menu.o_mne' => 'O mně',
    'menu.souhrn' => 'Souhrn',
    'menu.sluzby' => 'Služby',
    'menu.kontakt' => 'Kontakt',
    'menu.galerie' => 'Galerie',
    'menu.blog' => 'Blog',
    'paticka.o_mne' => 'O mně',
    'paticka.odkazy' => 'Odkazy',
    'paticka.sluzby' => 'Služby',
    'paticka.mate_otazku' => 'Máte otázku?',
];
