<?php

const TEXTY = [
    'hlavicka.ahoj' => 'Hey! I am',
    'hlavicka.ja_jsem' => 'I\'m a',
    'domu.o_mne.nadpis' => 'About Me',
    'domu.o_mne.popis' => 'A small river named Duden flows by their place and supplies it with the necessary regelialia.',
    'domu.o_mne.jmeno' => 'Name',
    'domu.o_mne.datum_narozeni' => 'Date of birth',
    'domu.o_mne.adresa' => 'Address',
    'domu.o_mne.email' => 'Email',
    'domu.o_mne.telefon' => 'Phone',
    'domu.souhrn.vzdelani' => 'Education',
    'domu.souhrn.zkusenosti' => 'Experience',
    'domu.souhrn.schopnosti' => 'Skills',
    'domu.sluzby.nadpis' => 'Services',
    'domu.sluzby.popis' => 'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia',
    'menu.domu' => 'Home',
    'menu.o_mne' => 'About me',
    'menu.souhrn' => 'Resume',
    'menu.sluzby' => 'Services',
    'menu.kontakt' => 'Contakt',
    'menu.galerie' => 'Gallery',
    'menu.blog' => 'Blog',
    'paticka.o_mne' => 'About',
    'paticka.odkazy' => 'Links',
    'paticka.sluzby' => 'Services',
    'paticka.mate_otazku' => 'Have a Questions?',
];
